spring:
  datasource:
    username: tomcat
    password: Mysql36383246@
    url: jdbc:mysql://ys.asterwyx.cn:3306/YuSchool?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 5
    max-active: 50
    max-wait: 60000

server:
  port: 80

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yuschool.bean